attrib -R *.* /S
attrib -R Hp
attrib -R Hp\s800
attrib -R Hp\s800\bin
attrib -R Hp\s800\include
attrib -R Hp\s800\lib
attrib -R Inferno
attrib -R Inferno\386
attrib -R Inferno\386\bin
attrib -R Inferno\386\include
attrib -R Inferno\386\lib
attrib -R Inferno\arm
attrib -R Inferno\arm\bin
attrib -R Inferno\arm\include
attrib -R Inferno\arm\lib
attrib -R Inferno\mips
attrib -R Inferno\mips\bin
attrib -R Inferno\mips\include
attrib -R Inferno\mips\lib
attrib -R Irix
attrib -R Irix\mips
attrib -R Irix\mips\bin
attrib -R Irix\mips\include
attrib -R Irix\mips\lib
attrib -R Nt
attrib -R Nt\386
attrib -R Nt\386\bin
attrib -R Nt\386\include
attrib -R Nt\386\lib
attrib -R Plan9
attrib -R Plan9\386
attrib -R Plan9\386\bin
attrib -R Plan9\386\include
attrib -R Plan9\386\lib
attrib -R Plan9\mips
attrib -R Plan9\mips\bin
attrib -R Plan9\mips\include
attrib -R Plan9\mips\lib
attrib -R Solaris
attrib -R Solaris\sparc
attrib -R Solaris\sparc\bin
attrib -R Solaris\sparc\include
attrib -R Solaris\sparc\lib
attrib -R appl
attrib -R appl\cmd
attrib -R appl\lib
attrib -R appl\limbo
attrib -R appl\math
attrib -R appl\mux
attrib -R appl\svc
attrib -R appl\svc\httpd
attrib -R appl\tcl
attrib -R appl\wm
attrib -R appl\wm\oldmods
attrib -R asm
attrib -R bin
attrib -R bin\386
attrib -R bin\mips
attrib -R chan
attrib -R crypt
attrib -R db
attrib -R dev
attrib -R dis
attrib -R dis\lib
attrib -R dis\math
attrib -R dis\mux
attrib -R dis\svc
attrib -R dis\svc\httpd
attrib -R dis\wm
attrib -R doc
attrib -R documentation
attrib -R documentation\architecture
attrib -R documentation\devl_guide
attrib -R documentation\installation
attrib -R documentation\language
attrib -R documentation\language\limbo_def
attrib -R documentation\language\limbo_def\icons
attrib -R documentation\language\limbo_tut
attrib -R documentation\language\limbo_tut\code
attrib -R documentation\language\limbo_tut\code2
attrib -R documentation\language\limbo_tut\code3
attrib -R documentation\language\limbo_tut\code4
attrib -R documentation\language\limbo_tut\code5
attrib -R documentation\language\limbo_tut\code6
attrib -R documentation\language\limbo_tut\code7
attrib -R documentation\language\limbo_tut\code8
attrib -R documentation\language\limbo_tut\code9
attrib -R documentation\man
attrib -R documentation\man\1
attrib -R documentation\man\2
attrib -R documentation\man\3
attrib -R documentation\man\4
attrib -R documentation\man\5
attrib -R documentation\man\6
attrib -R documentation\man\7
attrib -R documentation\man\8
attrib -R documentation\man\9
attrib -R documentation\man\man1
attrib -R documentation\man\man2
attrib -R documentation\man\man3
attrib -R documentation\man\man4
attrib -R documentation\man\man5
attrib -R documentation\man\man6
attrib -R documentation\man\man7
attrib -R documentation\man\man8
attrib -R documentation\man\man9
attrib -R emu
attrib -R fonts
attrib -R fonts\gb
attrib -R fonts\jis
attrib -R fonts\lucida
attrib -R fonts\lucidasans
attrib -R fonts\lucm
attrib -R fonts\misc
attrib -R fonts\pelm
attrib -R httpcache
attrib -R icons
attrib -R icons\rec-pb
attrib -R icons\tk
attrib -R icons\tk\debug
attrib -R image
attrib -R include
attrib -R interp
attrib -R keyring
attrib -R lib9
attrib -R libbio
attrib -R libk
attrib -R libregexp
attrib -R licensedb
attrib -R limbo
attrib -R locale
attrib -R man
attrib -R man\1
attrib -R man\2
attrib -R man\3
attrib -R man\4
attrib -R man\5
attrib -R man\6
attrib -R man\7
attrib -R man\8
attrib -R man\9
attrib -R man\html
attrib -R man\html\1
attrib -R man\html\2
attrib -R man\html\3
attrib -R man\html\4
attrib -R man\html\5
attrib -R man\html\6
attrib -R man\html\7
attrib -R man\html\8
attrib -R man\html\9
attrib -R man\html\man1
attrib -R man\html\man2
attrib -R man\html\man3
attrib -R man\html\man4
attrib -R man\html\man5
attrib -R man\html\man6
attrib -R man\html\man7
attrib -R man\html\man8
attrib -R man\html\man9
attrib -R man\man1
attrib -R man\man2
attrib -R man\man3
attrib -R man\man4
attrib -R man\man5
attrib -R man\man6
attrib -R man\man7
attrib -R man\man8
attrib -R man\man9
attrib -R math
attrib -R math\bin
attrib -R math\fdlibm
attrib -R memimage
attrib -R memlayer
attrib -R module
attrib -R movies
attrib -R mpeg
attrib -R mpeg\Drama
attrib -R mpeg\Sci-Fi
attrib -R mpeg\mpegserver
attrib -R n
attrib -R n\apwire
attrib -R n\client
attrib -R net
attrib -R os
attrib -R os\a7000
attrib -R os\init
attrib -R os\ip
attrib -R os\pc
attrib -R os\port
attrib -R os\proto
attrib -R prefab
attrib -R prog
attrib -R scripts
attrib -R scripts\bld.tools
attrib -R scripts\bld.tools\man.tools
attrib -R scripts\InstallShield
attrib -R scripts\InstallShield\setuplib
attrib -R services
attrib -R services\comics
attrib -R services\cs
attrib -R services\email
attrib -R services\httpd
attrib -R services\news
attrib -R services\news\lnw
attrib -R services\pizza
attrib -R services\pizza\gifs
attrib -R services\rec-pb
attrib -R services\tvlist
attrib -R services\web
attrib -R tk
attrib -R tools
attrib -R tools\bit2enc
attrib -R tools\bmp2enc
attrib -R tools\enc2bmp
attrib -R tools\gif2pic
attrib -R tools\gopher2html
attrib -R tools\include
attrib -R tools\jpg2pic
attrib -R tools\libfb
attrib -R tools\mpegd
attrib -R tools\tiff2pic
attrib -R tools\webget
attrib -R tools\xbm2pic
attrib -R usr
attrib -R usr\inferno
attrib -R utils
attrib -R utils\5a
attrib -R utils\5c
attrib -R utils\5l
attrib -R utils\8a
attrib -R utils\8c
attrib -R utils\8l
attrib -R utils\acid
attrib -R utils\ar
attrib -R utils\cc
attrib -R utils\mk
