<../mkconfig
<../$SYSHOST/mkhost
<../$OBJDIR/mkfile

LIB=libregexp.$A

OFILES=\
	regcomp.$O\
	regerror.$O\
	regexec.$O\
	regsub.$O\
	regaux.$O\
	rregexec.$O\
	rregsub.$O\

HFILES=\
	../include/regexp.h\
	regcomp.h\

<../$SYSTARG/mksyslib

test: test.$O $OFILES
	$LD -o test $prereq

test2: test2.$O $OFILES
	$LD -o test2 $prereq

package:QV:
	$TRUE
