!include ..\mkconfig.nmk
!include ..\$(SYSHOST)/mkhost
!include ..\$(OBJDIR)/makefile

LIB=libkeyring.$A

OFILES_C=\
	egalg.$O\

HFILES=\
	..\include\libcrypt.h\
	..\interp\runt.h\
	keys.h\

!include ..\$(SYSTARG)/mksyslib.nmk
