!include ..\..\..\mkconfig.nmk
!include ..\..\..\$(SYSHOST)\mkhost
!include ..\..\..\$(OBJDIR)\makefile

dotodir=.

CC_LOCAL=  -D_POSIX_ 
LIB=libbio.$A
OFILES_C=\
	$(dotodor)\2.$O\
	$(dotodor)\4.$O\
	$(dotodor)\6.$O\
	$(dotodor)\8.$O\
	$(dotodor)\9.$O\
	$(dotodor)\k.$O\
	$(dotodor)\v.$O\
	$(dotodor)\x.$O\
	$(dotodor)\2db.$O\
	$(dotodor)\4db.$O\
	$(dotodor)\6db.$O\
	$(dotodor)\8db.$O\
	$(dotodor)\9db.$O\
	$(dotodor)\kdb.$O\
	$(dotodor)\vdb.$O\
	$(dotodor)\map.$O\
	$(dotodor)\swap.$O\
	$(dotodor)\sym.$O\
	$(dotodor)\access.$O\
	$(dotodor)\machdata.$O\
	$(dotodor)\setmach.$O\
	$(dotodor)\executable.$O\
	$(dotodor)\vcodas.$O\

HFILES=mach.h a.out.h bootexec.h elf.h ureg2.h ureg4.h ureg8.h ureg9.h uregk.h uregv.h

!include ..\..\..\$(SYSHOST)\mksyslib.nmk

$(dotodor)\2.$O:	2.c
$(dotodor)\4.$O:	4.c
$(dotodor)\6.$O:	6.c
$(dotodor)\8.$O:	8.c
$(dotodor)\9.$O:	9.c
$(dotodor)\k.$O:	k.c
$(dotodor)\v.$O:	v.c
$(dotodor)\x.$O:	x.c
$(dotodor)\2db.$O:	2db.c
$(dotodor)\4db.$O:	4db.c
$(dotodor)\6db.$O:	6db.c
$(dotodor)\8db.$O:	8db.c
$(dotodor)\9db.$O:	9db.c
$(dotodor)\kdb.$O:	kdb.c
$(dotodor)\vdb.$O:	vdb.c
$(dotodor)\map.$O:	map.c
$(dotodor)\swap.$O:	swap.c
$(dotodor)\sym.$O:	sym.c
$(dotodor)\access.$O:	access.c
$(dotodor)\machdata.$O:	machdata.c
$(dotodor)\setmach.$O:	setmach.c
$(dotodor)\executable.$O:	executable.c
$(dotodor)\vcodas.$O:	vcodas.c
