<../../../mkconfig
<../../../$SYSHOST/mkhost
<../../../$OBJDIR/mkfile

LIB=libmach.$A
OFILES=\
	2.$O\
	4.$O\
	6.$O\
	8.$O\
	9.$O\
	k.$O\
	v.$O\
	x.$O\
	2db.$O\
	4db.$O\
	6db.$O\
	8db.$O\
	9db.$O\
	kdb.$O\
	vdb.$O\
	map.$O\
	swap.$O\
	sym.$O\
	access.$O\
	machdata.$O\
	setmach.$O\
	executable.$O\
	vcodas.$O\

HFILES=mach.h a.out.h bootexec.h elf.h ureg2.h ureg4.h ureg8.h ureg9.h uregk.h uregv.h

<../../../$SYSTARG/mksyslib
CFLAGS= $CFLAGS -9

package:QV:
	$TRUE
