SYSTARG=Inferno
OBJTYPE=386
CPUS=mips 386

A=		a8
O=		8
OS=		v 8 5 o

AR=		iar
ARFLAGS=	cvru

AS=		8a
ASFLAGS=

CC=		8c
CFLAGS=\
		-w\
		$(CC_LOCAL)\
		-I$(ROOT_DEVEL)\$(SYSTARG)\$(OBJTYPE)\include\
		-I$(ROOT_DEVEL)\include\

LD=		8l
LDFLAGS=
LDSYSLIBS=

YACC=		yacc
YFLAGS=		-d
