!include ..\mkconfig.nmk
!include ..\$(SYSHOST)\mkhost
!include ..\$(OBJDIR)\makefile

CC_LOCAL = 

LIB=lib9.$A

!include mkfile-$(SYSTARG)

HFILES=	$(ROOT_DEVEL)\$(SYSTARG)\$(OBJTYPE)\include\lib9.h

!include ..\$(SYSTARG)\mksyslib.nmk

